spring:
    datasource:
        url: jdbc:mysql://ml-mutant-prod.c0afqheabolw.us-east-1.rds.amazonaws.com:3306/mercadolibre?verifyServerCertificate=false&useSSL=false&requireSSL=false&createDatabaseIfNotExist=true
        username: mercadolibre
        password: mercadolibre
        driver-class-name: com.mysql.jdbc.Driver
com.ndamelio.mutant:
    sequence-to-found: 2
    min-length-sequence-dna: 4
logging.level.com.ndamelio.mutant: INFO